from app.models.module_registry import OsModule


MODULE_REGISTRY: tuple[OsModule, ...] = (
    OsModule(
        id="ai-home",
        label="AI首页",
        status="mvp",
        api_prefixes=["/api/v1/home"],
        capabilities=["经营概况", "利润总览", "现金流总览", "库存总览", "税务总览", "AI经营提示"],
        requires_permission=True,
        audit_events=["home.dashboard.read", "home.analyze.run"],
        rate_limit_policy="standard-read",
    ),
    OsModule(
        id="finance-center",
        label="AI财务中心",
        status="mvp",
        api_prefixes=[
            "/api/v1/vouchers",
            "/api/v1/accounting",
            "/api/v1/ledger",
            "/api/v1/fixed-assets",
            "/api/v1/fixed-asset-accounting",
            "/api/v1/payroll",
            "/api/v1/payroll-accounting",
            "/api/v1/period-close",
            "/api/v1/financial-statements",
            "/api/v1/accounting-archive",
            "/api/v1/receivable-payable",
            "/api/v1/bank-reconciliation",
            "/api/v1/dashboard/report",
        ],
        capabilities=["智能记账", "凭证中心", "总账", "往来核算", "银行对账", "固定资产", "固定资产正式核算", "工资管理", "薪酬正式核算", "财务报表"],
        requires_permission=True,
        audit_events=[
            "voucher.create",
            "voucher.review",
            "voucher.unreview",
            "voucher.post",
            "voucher.unpost",
            "accounting.account.read",
            "accounting.currency.read",
            "accounting.exchange_rate.read",
            "accounting.exchange_rate.write",
            "accounting.dimension.read",
            "accounting.dimension.write",
            "accounting.entry.read",
            "accounting.entry.post",
            "accounting.entry.reverse",
            "period_close.run_started",
            "period_close.runs_viewed",
            "period_close.checks_completed",
            "period_close.actions_previewed",
            "period_close.actions_generated",
            "period_close.period_closed",
            "period_close.period_reopened",
            "ledger.account_sets.read",
            "ledger.periods.read",
            "ledger.period.close",
            "ledger.period.reopen",
            "ledger.general.read",
            "ledger.detail.read",
            "ledger.account_balances.read",
            "fixed_asset.list",
            "fixed_asset.create",
            "fixed_asset.depreciation.run",
            "fixed_asset.dispose",
            "fixed_asset.sell",
            "fixed_asset.inventory",
            "fixed_asset_accounting.card.read",
            "fixed_asset_accounting.capitalize",
            "fixed_asset_accounting.depreciation.post",
            "fixed_asset_accounting.impairment.post",
            "fixed_asset_accounting.disposal.post",
            "payroll.calculate",
            "payroll_accounting.batch.read",
            "payroll_accounting.accrual.post",
            "payroll_accounting.payment.post",
            "payroll_accounting.liability_payment.post",
            "statement.generate",
            "statement.validate",
            "statement.mapping.view",
            "statement.mapping.update",
            "statement.snapshot.create",
            "statement.snapshot.lock",
            "statement.archive.view",
            "statement.export",
            "archive.document.list",
            "archive.document.get",
            "archive.document.create",
            "archive.case.create",
            "archive.package.download",
            "archive.verification.update",
            "receivable_payable.balance.read",
            "receivable_payable.aging.read",
            "receivable_payable.settle",
            "receivable_payable.bad_debt.provision",
            "bank_reconciliation.statement.import",
            "bank_reconciliation.match.suggest",
            "bank_reconciliation.match.confirm",
            "bank_reconciliation.statement.read",
            "report.export",
        ],
        rate_limit_policy="standard-write",
    ),
    OsModule(
        id="tax-center",
        label="AI税务中心",
        status="planned",
        api_prefixes=["/api/v1/tax"],
        capabilities=["增值税", "企业所得税", "个税", "优惠政策识别", "税务风险识别", "政策依据引用"],
        requires_permission=True,
        audit_events=["tax.calculate", "tax.policy.match", "tax.risk.detect"],
        rate_limit_policy="standard-write",
    ),
    OsModule(
        id="analysis-center",
        label="AI经营分析中心",
        status="mvp",
        api_prefixes=["/api/v1/dashboard"],
        capabilities=["利润趋势", "收入趋势", "费用趋势", "成本趋势", "现金流趋势", "经营报告"],
        requires_permission=True,
        audit_events=["analysis.overview.read", "analysis.report.generate"],
        rate_limit_policy="standard-read",
    ),
    OsModule(
        id="bi-center",
        label="BI数据中心",
        status="mvp",
        api_prefixes=["/api/v1/dashboard"],
        capabilities=["数据驾驶舱", "销售驾驶舱", "税务驾驶舱", "库存驾驶舱", "老板驾驶舱", "点击钻取分析"],
        requires_permission=True,
        audit_events=["bi.dashboard.read", "bi.drilldown.run"],
        rate_limit_policy="standard-read",
    ),
    OsModule(
        id="ecommerce-center",
        label="电商分析中心",
        status="mvp",
        api_prefixes=["/api/v1/ecommerce"],
        capabilities=["SKU利润分析", "广告ROI分析", "退货率分析", "物流成本分析", "平台费用分析", "爆款分析"],
        requires_permission=True,
        audit_events=["ecommerce.profit.analyze"],
        rate_limit_policy="analysis-heavy",
    ),
    OsModule(
        id="ocr-center",
        label="OCR识别中心",
        status="mvp",
        api_prefixes=["/api/v1/invoice-ocr"],
        capabilities=["增值税发票识别", "普通发票识别", "银行回单识别", "合同识别", "字段提取", "凭证建议"],
        requires_permission=True,
        audit_events=["ocr.text.recognize", "ocr.file.upload"],
        rate_limit_policy="upload-limited",
    ),
    OsModule(
        id="knowledge-base",
        label="企业知识库",
        status="mvp",
        api_prefixes=["/api/v1/policies"],
        capabilities=["PDF知识库", "Word知识库", "Excel知识库", "RAG检索", "版本管理", "来源追踪"],
        requires_permission=True,
        audit_events=["knowledge.search", "knowledge.source.read"],
        rate_limit_policy="standard-read",
    ),
    OsModule(
        id="ai-assistant",
        label="AI智能助手",
        status="mvp",
        api_prefixes=["/api/v1/finance-qa"],
        capabilities=["聊天问答", "文档分析", "Excel分析", "指标解释", "经营建议", "系统工具调用"],
        requires_permission=True,
        audit_events=["assistant.ask", "assistant.tool.invoke"],
        rate_limit_policy="llm-limited",
    ),
    OsModule(
        id="risk-center",
        label="风险预警中心",
        status="mvp",
        api_prefixes=["/api/v1/dashboard/risks", "/api/v1/audit"],
        capabilities=["税务风险", "库存风险", "利润异常", "现金流风险", "费用异常", "风险闭环跟踪"],
        requires_permission=True,
        audit_events=["risk.read", "audit.review"],
        rate_limit_policy="standard-read",
    ),
    OsModule(
        id="system-admin",
        label="系统管理",
        status="planned",
        api_prefixes=["/api/v1/system"],
        capabilities=["用户管理", "角色管理", "权限策略", "审计日志", "账套配置", "插件管理"],
        requires_permission=True,
        audit_events=["system.user.write", "system.role.write", "system.plugin.configure"],
        rate_limit_policy="admin-limited",
    ),
    OsModule(
        id="open-platform",
        label="开放平台（API）",
        status="planned",
        api_prefixes=["/api/v1/platform"],
        capabilities=["REST API", "Webhook", "OAuth2", "OpenAPI", "SDK", "权限控制", "审计日志", "限流", "版本管理"],
        requires_permission=True,
        audit_events=["platform.client.create", "platform.webhook.configure", "platform.token.issue"],
        rate_limit_policy="tenant-quota",
    ),
)


def list_modules() -> list[OsModule]:
    return list(MODULE_REGISTRY)


def get_module(module_id: str) -> OsModule | None:
    return next((module for module in MODULE_REGISTRY if module.id == module_id), None)
